DROP TABLE EQUIPAMIENTO  ;
DROP TABLE RECAMBIO  ;
DROP TABLE MOTOR  ;
DROP TABLE LINEAPEDIDO  ;
DROP TABLE PRODUCTO  ;
DROP TABLE PROVEEDOR  ;
DROP TABLE PEDIDO  ;
DROP TABLE CITA  ;
DROP TABLE VALORACION  ;
DROP TABLE CLIENTE  ;
DROP TABLE GERENTE  ;
DROP TABLE DEPENDIENTE  ;
DROP TABLE USUARIO  ;

CREATE TABLE USUARIO(
  email VARCHAR2(50) NOT NULL UNIQUE,
  contraseña VARCHAR(25),
  telefono NUMBER(9) NOT NULL UNIQUE,
  tipoUsuario VARCHAR2(25) CHECK( tipoUsuario IN('Cliente','Gerente','Dependiente')),
  OID_Us NUMBER(9) NOT NULL, 
  PRIMARY KEY(OID_Us),
  constraint contraseña CHECK (REGEXP_LIKE(contraseña,'[[:alnum:]]')),
  constraint contraseñaSoloNumeros CHECK
  (REGEXP_LIKE(contraseña,'[[:alpha:]]')),
  constraint contraseñaSoloLetras CHECK
  (REGEXP_LIKE(contraseña,'[[:digit:]]'))
);

CREATE TABLE CLIENTE(
  nombre VARCHAR2(25) NOT NULL,
  primerApellido VARCHAR2(25) NOT NULL,
  segundoApellido VARCHAR2(25) NOT NULL,
  dni VARCHAR2(9) NOT NULL UNIQUE,  
  direccion VARCHAR2(25) NOT NULL,
  OID_Us NUMBER(9) NOT NULL, 
  PRIMARY KEY(OID_Us),
  FOREIGN KEY(OID_Us) REFERENCES USUARIO ON DELETE CASCADE,
  CONSTRAINTS dni CHECK(REGEXP_LIKE(DNI, '^(\d{8}([A-Z]|[a-z]))$'))
);

CREATE TABLE DEPENDIENTE(
  OID_Us NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_Us),
  FOREIGN KEY(OID_Us) REFERENCES USUARIO ON DELETE CASCADE
);

CREATE TABLE GERENTE(
  OID_Us NUMBER(9) NOT NULL, 
  PRIMARY KEY(OID_Us),
  FOREIGN KEY(OID_Us) REFERENCES USUARIO ON DELETE CASCADE
);

CREATE TABLE VALORACION(
  asunto VARCHAR(55) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  fechaEnvio DATE DEFAULT SYSDATE,
  OID_V NUMBER(9) NOT NULL,
  OID_Us NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_V),
  FOREIGN KEY(OID_Us) REFERENCES USUARIO ON DELETE CASCADE
);

CREATE TABLE CITA(
  fechaAcordada DATE NOT NULL,
  asunto VARCHAR(55) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  tipoCita VARCHAR2(25) CHECK( tipoCita IN('Tienda', 'Taller')),
  OID_Ci NUMBER(9) NOT NULL,
  OID_Us NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_Ci),
  FOREIGN KEY(OID_Us) REFERENCES USUARIO ON DELETE CASCADE
);

CREATE TABLE PROVEEDOR(
  codigo VARCHAR(7) NOT NULL UNIQUE,
  nombre VARCHAR(25) NOT NULL,
  email VARCHAR(30) UNIQUE,
  telefono VARCHAR2(9) NOT NULL UNIQUE,
  direccion VARCHAR2(50),
  web VARCHAR(50),
  OID_Prov NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_Prov)
);

CREATE TABLE PEDIDO(
  fechaRealizacion DATE DEFAULT SYSDATE,
    fechaEntrega DATE,
  envio VARCHAR2(25) CHECK( envio IN('True', 'False')),
  tipoPago VARCHAR2(25) CHECK( tipoPago IN('Tarjeta', 'Transferencia')),
  estado VARCHAR2(25) DEFAULT 'Espera' CHECK( estado IN('Espera', 'Transito', 'Entregado')),
  precioTotal NUMBER(12,2) DEFAULT 0,
  OID_Pe NUMBER(9) NOT NULL,
  OID_Us NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_Pe),
  FOREIGN KEY(OID_Us) REFERENCES USUARIO ON DELETE CASCADE
);
  
CREATE TABLE PRODUCTO(
  codigo VARCHAR2(9) NOT NULL UNIQUE,
  nombre VARCHAR2(50) NOT NULL,
  descripcion VARCHAR2(500) NOT NULL,
  marca VARCHAR2(50),
  tipoProducto VARCHAR2(25) CHECK( tipoProducto IN('Equipamiento', 'Motor', 'Recambio')),
  precio NUMBER(*,2) NOT NULL,
  oferta NUMBER(*,2) DEFAULT 0,
  iva NUMBER(*,2) NOT NULL,
  stock NUMBER(2) NOT NULL,
  stockMinimo NUMBER(2) NOT NULL,
  OID_P NUMBER(9) NOT NULL,
  OID_Prov NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_P),
  FOREIGN KEY(OID_Prov) REFERENCES PROVEEDOR ON DELETE CASCADE,
  CONSTRAINT stockNegativo CHECK(stock>0 or stock=0)
);

CREATE TABLE LINEAPEDIDO(
  cantidad NUMBER(2,0) NOT NULL,
  precio NUMBER(10,2) NOT NULL,
  iva NUMBER(*,2) NOT NULL,
  OID_LP NUMBER(9) NOT NULL,
  OID_P NUMBER(9) NOT NULL,
  OID_Pe NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_LP),
  FOREIGN KEY(OID_P) REFERENCES PRODUCTO ON DELETE CASCADE,
  FOREIGN KEY(OID_Pe) REFERENCES PEDIDO ON DELETE CASCADE
);

CREATE TABLE MOTOR(
  cilindrada VARCHAR2(25) NOT NULL,
  estado VARCHAR2(25) CHECK( estado IN('Nuevo', 'Seminuevo', 'Segunda mano')),
  anyoFabricacion NUMBER(4,0) NOT NULL,
  tipoMotor VARCHAR2(25) CHECK( tipoMotor IN('Moto', 'Maquinaria')),
  garantia NUMBER(1,0),
  OID_P NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_P),
  FOREIGN KEY(OID_P) REFERENCES PRODUCTO ON DELETE CASCADE,
  CONSTRAINT maximoGarantia CHECK(garantia>=0 OR garantia<=7)
);

CREATE TABLE EQUIPAMIENTO(
  color VARCHAR2(50) NOT NULL,
  material VARCHAR2(50) NOT NULL,
  talla VARCHAR2(25) NOT NULL,
  OID_P NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_P),
  FOREIGN KEY(OID_P) REFERENCES PRODUCTO ON DELETE CASCADE
);

CREATE TABLE RECAMBIO(
  OID_P NUMBER(9) NOT NULL,
  PRIMARY KEY(OID_P),
  FOREIGN KEY(OID_P) REFERENCES PRODUCTO ON DELETE CASCADE
);
