DROP SEQUENCE sec_usuario;
DROP SEQUENCE sec_valoracion;
DROP SEQUENCE sec_cita;
DROP SEQUENCE sec_pedido;
DROP SEQUENCE sec_lineaPedido;
DROP SEQUENCE sec_producto;
DROP SEQUENCE sec_proveedor;
DROP SEQUENCE sec_equipamiento;

CREATE SEQUENCE sec_usuario INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_valoracion INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_cita INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_pedido INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_lineaPedido INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_producto INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_proveedor INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE sec_equipamiento INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER crea_oid_usuario
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
:NEW.OID_Us:=sec_usuario.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER crea_oid_valoracion
BEFORE INSERT ON VALORACION
FOR EACH ROW
BEGIN
:NEW.OID_V:=sec_valoracion.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER crea_oid_cita
BEFORE INSERT ON CITA
FOR EACH ROW
BEGIN
:NEW.OID_Ci:=sec_cita.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER crea_oid_pedido
BEFORE INSERT ON PEDIDO
FOR EACH ROW
BEGIN
:NEW.OID_Pe:=sec_pedido.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER crea_oid_lineaPedido
BEFORE INSERT ON LINEAPEDIDO
FOR EACH ROW
BEGIN
:NEW.OID_LP:=sec_lineaPedido.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER crea_oid_producto
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
:NEW.OID_P:=sec_producto.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER crea_oid_proveedor
BEFORE INSERT ON PROVEEDOR
FOR EACH ROW
BEGIN
:NEW.OID_Prov:=sec_proveedor.NEXTVAL;
END;
/



